### PR TITLE
Summer postgrads

### PR DESCRIPTION
**Pull request by Faiz**
this pr allows summer pg people to access roomie. only until september 30th

### CODE REVIEW

**Comment by Faiz** [comment]
sure let me try with fakeshib

**Comment by Faiz** [comment]
wait i just realised i dont know how to run roomie with fakeshib, i have to do some dodgy shit in react?

**Comment by ChristopherHammond13** [comment]
@Faiz let's test in prod lmao

**Comment by jermenkoo** [comment]
how the hell this got merged without tests

**Pull request merged**
